version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio_db
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: npm run start:dev

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    ports:
      - '3001:3000'
    depends_on:
      - backend
    command: npm run start-watch
    environment:
      - CHOKIDAR_USEPOLLING=true
